## Preferences

# start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1

# renumber all windows when any window is closed
set -g renumber-windows on

# use vi mode
setw -g mode-keys vi

# allows for faster key repetition
set -sg escape-time 0

# history
set -g history-limit 1000000

# dont exit from tmux when closing a session
set -g detach-on-destroy off

# display messages for 4 seconds
set -g display-time 4000


## Appearance

set-option -g default-terminal 'screen-254color'
set-option -g terminal-overrides ',xterm-256color:RGB'
set -g default-terminal "${TERM}"

# command / message line
set -g message-style fg=green,bg=black

# window-status-current
setw -g window-status-current-style bg=black,fg=green

# status bar
set -g status-bg black
set -g status-fg cyan
set -g status-left '#[fg=cyan]#S '
set -g status-right ''


## Keybindings

# remove ALL keybindings
unbind-key -a

# prefix
set -g prefix C-a


# Global bindings

bind-key C-a command-prompt
bind ! source-file ~/.tmux.conf \; display 'tmux reloaded'
bind-key C-c split-window -h -p 35 -c "#{pane_current_path}" "claude --continue"


# Session management

bind R command-prompt -I "#S" { rename-session "%%" }
bind-key -n M-J switch-client -p
bind-key -n M-K switch-client -n
bind T new-session
bind d detach-client
bind s choose-tree -Zs  # interactive session/window picker


# Window management

bind r command-prompt -I "#W" { rename-window "%%" }
bind t new-window -c "#{pane_current_path}"
bind-key -n M-j previous-window
bind-key -n M-k next-window
bind-key a last-window


# Pane management

bind g split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"
bind b break-pane        # move pane to a new window
bind f resize-pane -Z    # toggle fullscreen
bind x confirm-before -p "kill-pane #P? (y/n)" kill-pane
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5


# Vim mode

bind Escape copy-mode
bind p paste-buffer
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle  # block selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi J send-keys -X scroll-down
bind-key -T copy-mode-vi K send-keys -X scroll-up
bind-key -T copy-mode-vi g send-keys -X history-top
bind-key -T copy-mode-vi G send-keys -X history-bottom
bind-key -T copy-mode-vi / command-prompt -p "search down" { send-keys -X search-forward "%%" }
bind-key -T copy-mode-vi ? command-prompt -p "search up" { send-keys -X search-backward "%%" }
bind-key -T copy-mode-vi n send-keys -X search-again
bind-key -T copy-mode-vi N send-keys -X search-reverse      # search in opposite direction


# set environment variables
run '~/.dotfiles/tmux/setenv.tmux'


## Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'Morantron/tmux-fingers'

set -g @fingers-key space
set -g @fingers-jump-key j

# initialize tmux plugin manager
run '~/.tmux/plugins/tpm/tpm'

